### ISSUE TITLE
Adjust button text

### ISSUE THREAD

**Issue by mathvaleriano** [worknenjoy/gitpay#655] opened 2020-05-16 00:31 UTC
Button text is broken

### Why
Improve reading

### Level
Beginner

### Current behavior
Buttons of bounty area have broken texts

### Expected behavior
Need to pass another text or adjust button size 

### Useful links
https://gitpay.me/#/task/339

### Screenshot attached
some screenshot
![image](https://user-images.githubusercontent.com/12265496/82105750-4a8a0500-96f3-11ea-93e0-e949ea7e7c22.png)
![image](https://user-images.githubusercontent.com/12265496/82105754-5249a980-96f3-11ea-8b4c-1a6f4c2ceeda.png)

### How to reproduce the user scenario
Access the link and scroll down to see the buttons on the right side

**Comment by alexanmtz** [comment] 2020-05-18 12:19
Thanks for reporting this @mathvaleriano 🙏

**Comment by EANimesha** [comment] 2020-07-05 07:55
I am interested

**Comment by alexanmtz** [comment] 2020-07-05 10:44
Hello @EANimesha, that would be great! You're now assigned and you can start to work on this issue 👍

**Comment by EANimesha** [comment] 2020-07-05 16:43
Is the issue is still there?
When I am checking that was ok.

![Capture-gitpay](https://user-images.githubusercontent.com/37245819/86537400-66986e80-bf0c-11ea-9e0c-e09fe71c0aa0.PNG)

**Comment by alexanmtz** [comment] 2020-07-06 13:12
@EANimesha the button text should be always in one line, so the bug happens if we have larger texts. Maybe is a defined width, so we need to fix the wrap line when the text is large

**Comment by alexanmtz** [comment] 2020-07-29 17:50
@EANimesha any updates on this?

**Comment by Uttkarsh-Srivastava** [comment] 2020-08-07 18:40
@alexanmtz  I would like to work on this if it is available.

**Comment by alexanmtz** [comment] 2020-08-08 10:44
Yes please @Uttkarsh-Srivastava, you're now assigned 👍

**Comment by Simran-Chaudhary** [comment] 2020-08-29 04:35
Hey, if it's not yet fixed, I'd like to work on it. Just one question. Should the button width be flexible or we should change the font size for text to fit in one line?

**Comment by alexanmtz** [comment] 2020-08-29 21:13
Hey @Simran-Chaudhary, thanks for your interest, I will assign to you, and the width should be flexible, following the text size, but as a small button, it keeps a small height

So, happy coding 💻

**Comment by alexanmtz** [comment] 2020-09-18 19:36
Are still looking into this @Simran-Chaudhary ?

**Comment by Simran-Chaudhary** [comment] 2020-09-18 19:37
@alexanmtz I'm not able to reproduce the same. Could you help me with that?

**Comment by alexanmtz** [comment] 2020-09-18 19:42
@Simran-Chaudhary can you see the "Make an offer" wrapping in two lines? It should be one line, so we need to make the buttons adjustable.

**Comment by alexanmtz** [comment] 2020-09-24 18:47
You will complete this one @Simran-Chaudhary ?

Maybe there's some fixed width or some wrap property making the button break the line.

**Comment by djl218** [comment] 2020-10-23 23:38
Can I take a shot at this?

**Comment by djl218** [comment] 2020-10-24 01:26
Woohoo! I got it!

https://prnt.sc/v5pc24

**Comment by alexanmtz** [comment] 2020-10-24 09:35
Great @djl218 🎉 , please send a PR so we can proceed with your solution 👍

**Comment by djl218** [comment] 2020-10-24 10:35
I thought that I did submit a PR.  Did I do it right?

**Closed** 2020-10-25 12:27 UTC
Labels: beginner, bug, starter
