### ISSUE TITLE
Task grid filter doesn't work correctly

### ISSUE THREAD

**Issue by mthais** [worknenjoy/gitpay#340] opened 2019-03-22 19:14 UTC
The filter isn't working correctly. When the user selects the option "Created by me" the system returns all registers created by others authors, when the user select the option "I'm Interested" the system returns all tasks created on the system. It's necessary to change the filter to work according their specific action.

### Why
The user needs to filter the task to know about their information.

### Level
Medium 

### Current behavior
When the user does some filter on the tasks grid, the system returns the wrong information.

### Expected behavior
When the user does some filter on the tasks grid, the system should return the information according to their action. Check the image below to view the option in the screenshot attached.

### useful links
  N/A

### Screenshot attached
**Current behavior**

![Screen Shot 2019-04-22 at 16 56 50](https://user-images.githubusercontent.com/27444220/56524966-b6199700-6520-11e9-9035-e39efc5325d4.png)

**Expected behavior**

![Screen Shot 2019-03-27 at 09 40 17](https://user-images.githubusercontent.com/27444220/55077307-2c3bf280-5076-11e9-9f9e-02b71dd93d9e.png)

### How to solve this issue
 - Steps to solve 

### How to reproduce the user scenario

- Log in the platform;
- Click on the button "See tasks";
The system will show the  tasks grid;  

### What you will need to complete this issue
N/A

### Tips
When you finish the task, send us the print screen of the test evidence.

**Comment by VictorAlessander** [comment] 2019-06-15 23:44
Greetings.

This issue is already solved?

**Comment by mthais** [comment] 2019-06-19 14:08
@VictorAlessander Not yet. Do you want to contribute?

**Comment by VictorAlessander** [comment] 2019-06-22 21:37
Yes. Would be great!

Now I'm setting up the project on my workspace. This issue have a deadline?

**Comment by alexanmtz** [comment] 2019-06-23 20:51
There's no deadline @VictorAlessander, let me know if you need any help here or on our slack channel

**Comment by VictorAlessander** [comment] 2019-06-28 01:51
I don't know if the correct is to tell for you guys what's happened or just open a pull request. If is just open an pull request, please, tell me and I will go right to the point and not explain the cause of other bug again.

Well, I was able to reproduce the bug. Happens basically because for example, changing the language of user, triggers the ComponentDidUpdate. But ComponentDidUpdate will call the method **listTasks()** as the last thing to do, changing the task prop that are correct (filtered) to a "wrong value". So, the method "listTasks" will get all tasks, independent of what is the current tab. If the current tab is the zero (All tasks), doesn't seems a bug, but when isn't, the bug appears.

Should we discuss the way to fix or I can open a pull request and there we will discuss about? Because currently I have two ways to fix this.
We can discuss if exists a better way to fix different of the code that I will propose.
It would be nice. For me, feedbacks are always welcome.

**Comment by alexanmtz** [comment] 2019-06-28 08:35
Thanks for the suggestions @VictorAlessander , I would go with the suggestion two, it's better handled and with less conditionals flows (if / else and switch)

You can proceed with a Pull request from that one, from the Pull Request we will create a review app from your changes where @mthais can test, and we will use your seed to create the initial setup :-)

**Comment by VictorAlessander** [comment] 2019-06-29 02:01
Pull request created :tada:

**Comment by alexanmtz** [comment] 2019-07-01 08:50
Great @VictorAlessander , we have now a review app from your Pull Request and we will check, please test the app @mthais https://github.com/worknenjoy/gitpay/pull/377

**Comment by alexanmtz** [comment] 2019-07-02 18:49
Merged and deployed 🚀 

Thanks for the great contribution @VictorAlessander

**Closed by alexanmtz** 2019-07-02 18:49 UTC
Labels: React, bug, contribution, medium, node.js
